apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rest-http
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rest-http
    app.kubernetes.io/part-of: nodejs-rest-http
  name: nodejs-rest-http
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-rest-http
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-rest-http
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bgriggs-tenant/nodejs-rest-http/nodejs-rest-http@sha256:96111e4a5cd467a8fe91f29e3c75c3ebc51dac8ceb0ce8d89266a53f5085ce51
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
